<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>EngineBattle</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>chessIcon.ico</ApplicationIcon>
	</PropertyGroup>
<ItemGroup>
		<PackageReference Include="Markdig" Version="0.41.1" />
		<PackageReference Include="MudBlazor" Version="8.5.1" />
		<PackageReference Include="Toolbelt.Blazor.HotKeys2" Version="6.0.1" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" /> 
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\ChessLibrary\ChessLibrary.fsproj" />
	</ItemGroup>

</Project>
   